Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: us-east-1a
      ImageId : ami-0df8c184d5f6ae949
      InstanceType: t2.micro
      SecurityGroups:
        - !ImportValue SSHSecurityGroupforOutputGroup

  