AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to empty and delete an S3 bucket as per the bucket name provided by users of this yaml script.

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 bucket to delete.

Resources:
  EmptyBucketFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3BucketAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                Resource:
                  - !Sub arn:aws:s3:::${BucketName}
                  - !Sub arn:aws:s3:::${BucketName}/*

  EmptyBucketFunction:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Handler: index.handler
      Role: !GetAtt EmptyBucketFunctionRole.Arn
      Code:
        ZipFile: |
          import boto3
          import os
          def handler(event, context):
              bucket_name = os.environ['BUCKET_NAME']
              s3 = boto3.resource('s3')
              bucket = s3.Bucket(bucket_name)
              # Empty the bucket
              bucket.object_versions.delete()
              return {"message": f"Emptied bucket {bucket_name}"}
      Timeout: 60
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName

  EmptyBucketCustomResource:
    Type: Custom::EmptyBucket
    Properties:
      ServiceToken: !GetAtt EmptyBucketFunction.Arn

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
    DeletionPolicy: Delete
    DependsOn: EmptyBucketCustomResource

Outputs:
  BucketStatus:
    Description: Status of the S3 bucket deletion process.
    Value: "The bucket will be emptied and deleted as per the provided name."
